# Generated by Django 3.2.6 on 2021-09-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('admno', models.IntegerField()),
                ('rollno', models.IntegerField()),
                ('college', models.CharField(max_length=50)),
                ('parentname', models.CharField(max_length=50)),
                ('mobileno', models.BigIntegerField()),
                ('dept', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
