# Generated by Django 3.2.6 on 2021-08-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_code', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('addess', models.CharField(max_length=50)),
                ('disease', models.CharField(max_length=50)),
                ('admitstatus', models.DateField()),
            ],
        ),
    ]
