# Generated by Django 3.2.6 on 2021-09-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fcode', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('mobileno', models.BigIntegerField()),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
